In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import os, glob
import pickle

In [2]:
def load_data(folder_path):
    df = pd.DataFrame()
    for file_path in glob.glob(os.path.join(folder_path, "*.pkl")):
        with open(file_path, "rb") as f:
            df_line = pd.DataFrame([pickle.load(f)])
        df = pd.concat([df, df_line], ignore_index=True)
    # df = df.dropna(subset=["critical_load"])
    # df = df.sort_values("date", ascending=False)
    return df

In [5]:
folder_path = Path("output/")
data = load_data(folder_path)

In [6]:
data

   total_time                           type    N  n
0       25.36  distributed_jax_several_hosts   50  4
1      854.64                       standard  500  4
2      140.15  distributed_jax_several_hosts  200  4
3      139.34                       standard  200  4
4      857.18                distributed_jax  500  4
5      297.12                distributed_jax  300  4
6      791.88  distributed_jax_several_hosts  500  4
7      139.07                distributed_jax  200  4
8      300.66                       standard  300  4
9       22.76                distributed_jax   50  4